server:
  port: 8082

spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL
    register-with-eureka: true                     # Register this service with Eureka
    fetch-registry: true                           # Fetch registry info from server

  instance:
    hostname: localhost
    prefer-ip-address: true