spring:
  application:
    name: ai-service

server:
  port: 8083

  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendation
      database: airecommendation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL
    register-with-eureka: true                     # Register this service with Eureka
    fetch-registry: true                           # Fetch registry info from server

  instance:
    hostname: localhost
    prefer-ip-address: true

